MSSQL_HOST=127.0.0.1
MSSQL_PORT=1433
MSSQL_DB=ecommerce_mssql1
MSSQL_USER=sa
MSSQL_PASSWORD=Password@123

MSSQL_DRIVER_VERSION=12.10.0

MSSQL_ODBC_DRIVER="ODBC Driver 18 for SQL Server"

LIQUIBASE_VERSION=5.0.3

MSSQL_ACCEPT_EULA=True
MSSQL_PID=Developer
