POSTGRESQL_HOST=127.0.0.1
POSTGRESQL_PORT=5434
POSTGRESQL_DB=ecommerce_postgresql
POSTGRESQL_USER=postgres
POSTGRESQL_PASSWORD=root1234

POSTGRESQL_VERSION=17
POSTGRESQL_DRIVER_VERSION=42.7.3
LIQUIBASE_VERSION=5.0.3