SERVICE_MODEL=windows_service
SERVICE_NAME_PATTERN=MSSQL$%INSTANCE%
WINDOWS_SERVICE_NAME=MSSQLSERVER

TERRAFORM_DIRECTORY=terraform\mssql
TERRAFORM_RESOURCES=

CLEANUP_OWNERSHIP=platform

INSTALLATION_DIR=databases\mssql
RUNTIME_DATA_DIR=databases\mssql\data
RUNTIME_TEMP_DIR=outputs\temp\mssql

LIQUIBASE_ENABLED=true
LIQUIBASE_DIR=liquibase\mssql
LIQUIBASE_CHANGELOG=liquibase_mssql.xml

ARTIFACT_OWNERSHIP=cleanup
ARCHIVE_DIR=archive\mssql
FAILED_DIR=failed\mssql
INCOMING_DIR=incoming\mssql
HISTORY_FILE=metadata\mssql\data_load_history.jsonl

DROP_DATABASE_ENABLED_WINDOWS=true
RESET_TERRAFORM_ONLY=false
XML_CLEANUP_ENABLED=true
