SERVICE_MODEL=process
PROCESS_NAME=mysqld.exe
PROCESS_EXECUTABLE=databases\mysql\server\bin\mysqld.exe

TERRAFORM_DIRECTORY=terraform\mysql
TERRAFORM_RESOURCES=download_mysql_windows,extract_mysql_windows,init_mysql_windows,start_mysql_windows,create_mysql_user_windows

CLEANUP_OWNERSHIP=platform

INSTALLATION_DIR=databases\mysql
RUNTIME_DATA_DIR=databases\mysql\data
RUNTIME_TEMP_DIR=outputs\temp\mysql

LIQUIBASE_ENABLED=true
LIQUIBASE_DIR=liquibase\mysql
LIQUIBASE_CHANGELOG=liquibase_mysql.xml

ARTIFACT_OWNERSHIP=cleanup
ARCHIVE_DIR=archive\mysql
FAILED_DIR=failed\mysql
INCOMING_DIR=incoming\mysql
HISTORY_FILE=metadata\mysql\data_load_history.jsonl

CLEANUP_DATA_ENABLED_WINDOWS=true
RESET_TERRAFORM_ONLY=false
XML_CLEANUP_ENABLED=true
