#############################################
# Dataset Configuration
#############################################

# Archive Name
DATASET_NAME=testdatasmall.zip

# Download Directory
DOWNLOAD_DIRECTORY=incoming/archive

# Extract After Download
AUTO_EXTRACT=true

# Delete Archive After Extraction
DELETE_ARCHIVE=false

# Force Download Even If File Exists
FORCE_DOWNLOAD=false

# Force Extraction Even If Already Extracted
FORCE_EXTRACT=false