#############################################
# Dataset Configuration
#############################################

# Google Drive Direct Download URL
DATASET_URL=https://drive.google.com/file/d/1TYTRnsnRP-X4voxgit_QAOma2lQUyyU_/view?usp=drive_link
# Archive Name
DATASET_NAME=AutomationData_v3.zip

# Download Directory
DOWNLOAD_DIRECTORY=incoming/archive

# Extract After Download
AUTO_EXTRACT=true

# Delete Archive After Extraction
DELETE_ARCHIVE=false

# Force Download Even If File Exists
FORCE_DOWNLOAD=false



FORCE_EXTRACT=false
