DEFAULT_VIEW_LIMIT=10

DEFAULT_PROCEDURE_LIMIT=100

DEFAULT_INDEX_PREFIX=idx_

DEFAULT_VIEW_PREFIX=v_

DEFAULT_FUNCTION_PREFIX=fn_

DEFAULT_PROCEDURE_PREFIX=sp_

DEFAULT_TRIGGER_PREFIX=trg_

DEFAULT_EVENT_PREFIX=ev_

GENERATE_VIEWS=true

GENERATE_FUNCTIONS=true

GENERATE_PROCEDURES=true

GENERATE_TRIGGERS=true

GENERATE_EVENTS=true

GENERATE_INDEXES=true