MSSQL_HOST=localhost
MSSQL_PORT=1533
MSSQL_DB=ecommerce_mssql
MSSQL_USER=sa
MSSQL_PASSWORD=Password@123
MSSQL_INSTANCE=DMSQL
MSSQL_DRIVER_VERSION=12.10.0
MSSQL_ODBC_DRIVER=ODBC Driver 17 for SQL Server
