MSSQL_HOST=localhost
MSSQL_PORT=1533

MSSQL_DB=healthcare_mssql

MSSQL_USER=sa
MSSQL_PASSWORD=Password@123

MSSQL_INSTANCE=DMSQL

MSSQL_DRIVER_VERSION=12.10.0

MSSQL_ODBC_DRIVER=ODBC Driver 17 for SQL Server

LIQUIBASE_VERSION=5.0.3

# =====================================================
# SQL Server Installation
# =====================================================

MSSQL_FEATURES=SQLENGINE

MSSQL_SECURITY_MODE=SQL

MSSQL_ACCEPT_EULA=True

MSSQL_INSTALL_UPDATES=False

MSSQL_TCP_ENABLED=True

MSSQL_NP_ENABLED=False

MSSQL_SQLSVC_STARTUP=Automatic

MSSQL_AGTSVC_STARTUP=Manual

MSSQL_BROWSER_STARTUP=Automatic

MSSQL_SYSADMIN_ACCOUNTS=Administrators