#############################################
# MSSQL Installation Media
#############################################

# Google Drive Direct Download URL
MSSQL_MEDIA_URL=https://drive.google.com/file/d/1mFA62gYtN6NPiHOvPmoTSVh9g4ZhqAyO/view?usp=drive_link

# Archive Name
MSSQL_MEDIA_NAME=SQLServer2022Media.zip

# Download Directory
MSSQL_DOWNLOAD_DIRECTORY=databases/mssql/downloads

# Extract Directory
MSSQL_MEDIA_DIRECTORY=databases/mssql/media

# Extract After Download
AUTO_EXTRACT=true

# Delete Archive After Extraction
DELETE_ARCHIVE=false

# Force Download Even If File Exists
FORCE_DOWNLOAD=false

# Force Extraction Even If Media Exists
FORCE_EXTRACT=false